apiVersion: v1
kind: Pod
metadata:
  name: test-pod-alpine
  labels:
    app: test-alpine
spec:
  containers:
  - name: alpine-container
    image: alpine:latest
    command: ["sleep", "3600"]
  restartPolicy: Never
