apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - name: test-container
    image: 992382823327.dkr.ecr.us-west-2.amazonaws.com/caas-test/business-service1:alpine-latest
    command: ["sleep", "3600"]
  restartPolicy: Never
